### ISSUE TITLE
Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop

### ISSUE THREAD

**Issue by mnbf9rca** [jlesage/docker-cloudberry-backup#23] opened 2020-11-29 15:30 UTC
i have been using the container for about 2-3 months now, and recently went to take a look and found nothing was working. The pod logs look like this:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing... 
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing... 
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing... 
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing... 
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing... 
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing... 
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing... 
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing... 
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing... 
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing... 
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing... 
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing... 
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] cloudberrybackup.sh: executing... 
[cont-init.d] cloudberrybackup.sh: generating machine-id...
[cont-init.d] cloudberrybackup.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting nginx...
[services.d] starting certsmonitor...
[nginx] starting...
[services.d] starting xvfb...
[certsmonitor] disabling service: secure connection not enabled.
[xvfb] starting...
[services.d] starting cbbLocalManagement...
[cbbLocalManagement] starting...
[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop
[cbbLocalManagement] starting...
[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop
[cbbLocalManagement] starting...
[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop
[cbbLocalManagement] starting...
[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop
[cbbLocalManagement] starting...
[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop
s6-svwait: fatal: timed out
[services.d] starting cbbWebAccess...
[cbbWebAccess] starting...
[services.d] starting logmonitor...
[cbbLocalManagement] starting...
[logmonitor] no file to monitor: disabling service...
[services.d] starting statusmonitor...
[services.d] starting openbox...
[statusmonitor] starting...
[openbox] starting...
[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop
[cbbLocalManagement] starting...
[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop
[cbbLocalManagement] starting...
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting CloudBerry Backup...
29/11/2020 15:22:15 passing arg to libvncserver: -rfbport
29/11/2020 15:22:15 passing arg to libvncserver: 5900
29/11/2020 15:22:15 passing arg to libvncserver: -rfbportv6
29/11/2020 15:22:15 passing arg to libvncserver: -1
29/11/2020 15:22:15 passing arg to libvncserver: -httpportv6
29/11/2020 15:22:15 passing arg to libvncserver: -1
29/11/2020 15:22:15 passing arg to libvncserver: -desktop
29/11/2020 15:22:15 passing arg to libvncserver: CloudBerry Backup
29/11/2020 15:22:15 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 1872
29/11/2020 15:22:15 Using X display :0
29/11/2020 15:22:15 rootwin: 0x43 reswin: 0x400001 dpy: 0x4f5d29e0
29/11/2020 15:22:15 
29/11/2020 15:22:15 ------------------ USEFUL INFORMATION ------------------
[services.d] done.
29/11/2020 15:22:15 X DAMAGE available on display, using it for polling hints.
29/11/2020 15:22:15   To disable this behavior use: '-noxdamage'
29/11/2020 15:22:15 
29/11/2020 15:22:15   Most compositing window managers like 'compiz' or 'beryl'
29/11/2020 15:22:15   cause X DAMAGE to fail, and so you may not see any screen
29/11/2020 15:22:15   updates via VNC.  Either disable 'compiz' (recommended) or
29/11/2020 15:22:15   supply the x11vnc '-noxdamage' command line option.
29/11/2020 15:22:15 X COMPOSITE available on display, using it for window polling.
29/11/2020 15:22:15   To disable this behavior use: '-noxcomposite'
29/11/2020 15:22:15 
29/11/2020 15:22:15 Wireframing: -wireframe mode is in effect for window moves.
29/11/2020 15:22:15   If this yields undesired behavior (poor response, painting
29/11/2020 15:22:15   errors, etc) it may be disabled:
29/11/2020 15:22:15    - use '-nowf' to disable wireframing completely.
29/11/2020 15:22:15    - use '-nowcr' to disable the Copy Rectangle after the
29/11/2020 15:22:15      moved window is released in the new position.
29/11/2020 15:22:15   Also see the -help entry for tuning parameters.
29/11/2020 15:22:15   You can press 3 Alt_L's (Left "Alt" key) in a row to 
29/11/2020 15:22:15   repaint the screen, also see the -fixscreen option for
29/11/2020 15:22:15   periodic repaints.
29/11/2020 15:22:15 GrabServer control via XTEST.
29/11/2020 15:22:15 
29/11/2020 15:22:15 Scroll Detection: -scrollcopyrect mode is in effect to
29/11/2020 15:22:15   use RECORD extension to try to detect scrolling windows
29/11/2020 15:22:15   (induced by either user keystroke or mouse input).
29/11/2020 15:22:15   If this yields undesired behavior (poor response, painting
29/11/2020 15:22:15   errors, etc) it may be disabled via: '-noscr'
29/11/2020 15:22:15   Also see the -help entry for tuning parameters.
29/11/2020 15:22:15   You can press 3 Alt_L's (Left "Alt" key) in a row to 
29/11/2020 15:22:15   repaint the screen, also see the -fixscreen option for
29/11/2020 15:22:15   periodic repaints.
29/11/2020 15:22:15 
29/11/2020 15:22:15 XKEYBOARD: number of keysyms per keycode 7 is greater
29/11/2020 15:22:15   than 4 and 51 keysyms are mapped above 4.
29/11/2020 15:22:15   Automatically switching to -xkb mode.
29/11/2020 15:22:15   If this makes the key mapping worse you can
29/11/2020 15:22:15   disable it with the "-noxkb" option.
29/11/2020 15:22:15   Also, remember "-remap DEAD" for accenting characters.
29/11/2020 15:22:15 
29/11/2020 15:22:15 X FBPM extension not supported.
Xlib:  extension "DPMS" missing on display ":0".
29/11/2020 15:22:15 X display is not capable of DPMS.
29/11/2020 15:22:15 --------------------------------------------------------
29/11/2020 15:22:15 
29/11/2020 15:22:15 Default visual ID: 0x21
29/11/2020 15:22:15 Read initial data from X display into framebuffer.
29/11/2020 15:22:15 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
29/11/2020 15:22:15 
29/11/2020 15:22:15 X display :0 is 32bpp depth=24 true color
29/11/2020 15:22:15 
29/11/2020 15:22:15 Listening for VNC connections on TCP port 5900
29/11/2020 15:22:15 
29/11/2020 15:22:15 Xinerama is present and active (e.g. multi-head).
29/11/2020 15:22:15 Xinerama: number of sub-screens: 1
29/11/2020 15:22:15 Xinerama: no blackouts needed (only one sub-screen)
29/11/2020 15:22:15 
29/11/2020 15:22:15 fb read rate: 540 MB/sec
29/11/2020 15:22:15 fast read: reset -wait  ms to: 10
29/11/2020 15:22:15 fast read: reset -defer ms to: 10
29/11/2020 15:22:15 The X server says there are 10 mouse buttons.
29/11/2020 15:22:15 screen setup finished.
29/11/2020 15:22:15 

The VNC desktop is:      cloudberry-5cf74db59d-lv4f9:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop
[cbbLocalManagement] starting...
[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop
[cbbLocalManagement] starting...
```
and on forever. `/usr/share/applications/` doesn't contain `cloudberry-backup.desktop`, so it's hardly surprising that it can't read it:
```
/tmp # ls -al /usr/share/applications/
total 16
drwxr-xr-x    1 root     root          4096 Oct 20 22:51 .
drwxr-xr-x    1 root     root          4096 Oct 20 22:52 ..
-rw-r--r--    1 root     root           338 Dec 19  2018 openbox.desktop
-rw-r--r--    1 root     root           751 Dec 24  2018 yad-icon-browser.desktop
/tmp # 
```

i've tried re-pulling the image. Any ideas?

**Comment by jlesage** [comment] 2020-11-30 15:41
The `[ CBB ] [ 1 ] Error: can't read content of the file: /usr/share/applications/cloudberry-backup.desktop` message is probably not the cause of the issue, since it is always displayed even when working properly.

Can you look at `/config/logs/log_LocalDaemon.log` to see if there is more details about the failure ?

**Comment by jlesage** [comment] 2021-11-15 21:54
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2021-11-15 21:54 UTC
