### ISSUE TITLE
1.9.1 stops right after start up

### ISSUE THREAD

**Issue by timarthurlee** [jlesage/docker-cloudberry-backup#1] opened 2017-12-18 03:00 UTC
See log below:
```12/16/2017 1:47:36 PM[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
12/16/2017 1:47:36 PM[s6-init] ensuring user provided files have correct perms...exited 0.
12/16/2017 1:47:36 PM[fix-attrs.d] applying ownership & permissions fixes...
12/16/2017 1:47:36 PM[fix-attrs.d] done.
12/16/2017 1:47:36 PM[cont-init.d] executing container initialization scripts...
12/16/2017 1:47:36 PM[cont-init.d] 00-app-niceness.sh: executing...
12/16/2017 1:47:36 PM[cont-init.d] 00-app-niceness.sh: exited 0.
12/16/2017 1:47:36 PM[cont-init.d] 00-app-script.sh: executing...
12/16/2017 1:47:36 PM[cont-init.d] 00-app-script.sh: exited 0.
12/16/2017 1:47:36 PM[cont-init.d] 00-app-user-map.sh: executing...
12/16/2017 1:47:36 PM[cont-init.d] 00-app-user-map.sh: exited 0.
12/16/2017 1:47:36 PM[cont-init.d] 00-clean-tmp-dir.sh: executing...
12/16/2017 1:47:36 PM[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
12/16/2017 1:47:36 PM[cont-init.d] 00-set-app-deps.sh: executing...
12/16/2017 1:47:36 PM[cont-init.d] 00-set-app-deps.sh: exited 0.
12/16/2017 1:47:36 PM[cont-init.d] 00-set-home.sh: executing...
12/16/2017 1:47:36 PM[cont-init.d] 00-set-home.sh: exited 0.
12/16/2017 1:47:36 PM[cont-init.d] 00-take-config-ownership.sh: executing...
12/16/2017 1:47:36 PMchown: /config: Invalid argument
12/16/2017 1:47:36 PMchown: /config: Invalid argument
12/16/2017 1:47:36 PM[cont-init.d] 00-take-config-ownership.sh: exited 1.
12/16/2017 1:47:36 PM[services.d] stopping services
12/16/2017 1:47:36 PM[services.d] stopping s6-fdholderd...
12/16/2017 1:47:37 PM[cont-finish.d] executing container finish scripts...
12/16/2017 1:47:37 PM[cont-finish.d] done.
12/16/2017 1:47:37 PM[s6-finish] syncing disks.
12/16/2017 1:47:37 PM[s6-finish] sending all processes the TERM signal.
12/16/2017 1:47:40 PM[s6-finish] sending all processes the KILL signal and exiting.
```

Note: I am using rancher with an NFS share as the /config folder. I have also chowned the nfs share on the host to the same gid and uid as specified in the "USER_ID" and "GROUP_ID" environment variables on the docker container.

**Comment by jlesage** [comment] 2017-12-18 15:05
Is the container running if you don't map `/config`?  If yes, then it looks like a NFS mount permission issue.
On the host running the container, are you able to manually do the `chown` on the folder?

**Comment by timarthurlee** [comment] 2017-12-19 00:49
The config directory is already chown'd to the same gid and uid that is
specified in the container config. Should I be using a different gid/uid?

**Comment by jlesage** [comment] 2017-12-19 01:31
No, should be the same.
The container takes ownership of `/config` during startup.  This operation seems to fail.  So there are a couple of point of failures that could explain that.  For example, how you mounted the NFS share and how the user mapping was done on the NFS server can all cause the issue.
To find out where it's failing, I would do the following things:
  - Try to run the container without mapping `/config`.  It it's working, then the problem is really related to the mapping of `/config`.
  - On the host running the container, try to manually chown the folder mapped to `/config`.  Use the same uid/gid.  For example: `chown -R <uid>:<gid> /path/to/config`.

**Comment by jlesage** [comment] 2018-02-19 01:12
Closing the issue.  Feel free to re-open if you still have issues.

**Closed by jlesage** 2018-02-19 01:12 UTC
